// Admin Dashboard Actions
export const FETCH_ADMIN_DASHBOARD_DATA_SUCCESS = 'FETCH_ADMIN_DASHBOARD_DATA_SUCCESS';
export const FETCH_ADMIN_DASHBOARD_DATA_FAILURE = 'FETCH_ADMIN_DASHBOARD_DATA_FAILURE';

// User Actions
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
